### ISSUE TITLE
how to get the liner-gradient out of grid 

### ISSUE THREAD

**Issue by Jessica3860** [Jessica3860/svg-icon-sets#1]
hi Karen, 
how do I get the liner-gradient out of grid? 
@KarenMendozaGarza
![image](https://user-images.githubusercontent.com/83955882/155399791-7809e644-0502-4724-93f0-043d9f8d1b85.png)

**Comment by KarenMendozaGarza** [comment]
Hey Jessica,

You don't necessarily have to. My submission looked the same, and it shouldn't prevent markbot from giving you a pass. I can't see your code on github for some reason, perhaps you haven't committed yet, but you could try putting the gradient in whatever section holds your cards instead of whatever larger container you might have it in now. Again, I wouldn't worry too much unless markbot gives you any grief. 
<img width="1664" alt="Screen Shot 2022-02-23 at 3 14 17 PM" src="https://user-images.githubusercontent.com/77505891/155400610-622dee65-78b8-46e7-bdd9-469d2494c53d.png">

**Comment by Jessica3860** [comment]
thats good, thank you. @KarenMendozaGarza

also for this assignment should I have put my paragraphs/sections in un-orders list? because markbot does not like how i set up my html. or should they have been articles? 
![image](https://user-images.githubusercontent.com/83955882/155414288-0b1b1bd3-887e-4ced-93ce-3d85903c2d81.png)

**Comment by KarenMendozaGarza** [comment]
a list would not be appropriate for this content. An article would definitely be a better container, or just a div would do as well.

**Comment by Jessica3860** [comment]
ohh, okay thank you!
@KarenMendozaGarza

**Comment by Jessica3860** [comment]
one other question, do the images need to change colour when hovered over or just the "learn about" boxes at the bottom? @KarenMendozaGarza

**Comment by KarenMendozaGarza** [comment]
I believe it's just the learn about buttons

**Comment by Jessica3860** [comment]
lovely, thank you. was not sure

**Comment by KarenMendozaGarza** [comment]
Hi jessica, 
Please remember to close your issues when they have been resolved:)
